{
 "title": "sonar-dashboard",
 "tags": [
  "sonar",
  "influxdb"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sonarproject",
    "query": "SHOW TAG VALUES  WITH KEY = \"key\""
   }
  ]
 },
 "panels": [
  {
   "title": "last_analyzed_date",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 17, "x": 0, "y": 0 },
   "repeat": "sonarproject",
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "last_commit_date",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=~", "value": "/^$sonarproject$/" }
     ]
    }
   ]
  },
  {
   "title": "Code lines",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 17, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "lines",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=~", "value": "/^$sonarproject$/" }
     ]
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "sqale_rating",
   "type": "singlestat",
   "description": "{u'domain': u'Maintainability', u'description': u'A-to-E rating based on the technical debt ratio', u'qualitative': True, u'direction': -1, u'custom': False, u'key': u'sqale_rating', u'hidden': False, u'type': u'RATING', u'id': u'120', u'name': u'Maintainability Rating'}",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqale_rating",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=~", "value": "/^$sonarproject$/" }
     ]
    }
   ]
  },
  {
   "title": "coverage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "coverage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=~", "value": "/^$sonarproject$/" }
     ]
    }
   ]
  },
  {
   "title": "code_smells",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "code_smells",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=~", "value": "/^$sonarproject$/" }
     ]
    }
   ]
  },
  {
   "title": "Non commenting lines of code",
   "type": "singlestat",
   "description": "Non commenting lines of code",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ncloc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=~", "value": "/^$sonarproject$/" }
     ]
    }
   ]
  },
  {
   "title": "Bug",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bugs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=~", "value": "/^$sonarproject$/" }
     ]
    }
   ]
  },
  { "title": "Complexity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "complexity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "complexity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=~", "value": "/^$sonarproject$/" }
     ]
    }
   ]
  },
  {
   "title": "cognitive_complexity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cognitive_complexity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=~", "value": "/^$sonarproject$/" }
     ]
    }
   ]
  },
  {
   "title": "complexity_in_functions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "complexity_in_functions",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=~", "value": "/^$sonarproject$/" }
     ]
    }
   ]
  },
  {
   "title": "complexity_in_classes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "complexity_in_classes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=~", "value": "/^$sonarproject$/" }
     ]
    }
   ]
  },
  {
   "title": "file_complexity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 17, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "file_complexity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=~", "value": "/^$sonarproject$/" }
     ]
    }
   ]
  },
  {
   "title": "duplicated_lines",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "duplicated_lines_density",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=~", "value": "/^$sonarproject$/" }
     ]
    }
   ]
  },
  { "title": "Issues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "confirmed_issues",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "confirmed_issues",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=~", "value": "/^$sonarproject$/" }
     ]
    }
   ]
  },
  {
   "title": "false_positive_issues",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "false_positive_issues",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=~", "value": "/^$sonarproject$/" }
     ]
    }
   ]
  },
  {
   "title": "Issue Severity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "info_violations",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=~", "value": "/^$sonarproject$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "major_violations",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=~", "value": "/^$sonarproject$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "minor_violations",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=~", "value": "/^$sonarproject$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "critical_violations",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=~", "value": "/^$sonarproject$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "blocker_violations",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=~", "value": "/^$sonarproject$/" }
     ]
    }
   ]
  },
  {
   "title": "Code line",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "lines",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=~", "value": "/^$sonarproject$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "line_coverage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=~", "value": "/^$sonarproject$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "lines_to_cover",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=~", "value": "/^$sonarproject$/" }
     ]
    }
   ]
  },
  {
   "title": "YOUR-PROJECT bugs alert",
   "type": "graph",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "sso",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bugs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "sso-service:master" }
     ]
    },
    {
     "alias": "image-service",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bugs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "image_service:master" }
     ]
    },
    {
     "alias": "payment-service",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bugs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "payment-service" }
     ]
    }
   ]
  },
  {
   "title": "CCP sonar",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "poi-service",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bugs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "poi-service:master" }
     ]
    },
    {
     "alias": "recommand-service",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bugs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "recommend-service:master" }
     ]
    },
    {
     "alias": "customer-profile-v2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bugs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "customer-profile-v2:master" }
     ]
    }
   ]
  },
  {
   "title": "YOUR-PROJECT bugs alert",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "product-service",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bugs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "product-service:master" }
     ]
    },
    {
     "alias": "cms-service",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bugs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "cms-service:master" }
     ]
    },
    {
     "alias": "product-service",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bugs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "key",
       "operator": "=",
       "value": "YOUR-PROJECT-core-service:master"
      }
     ]
    },
    {
     "alias": "YOUR-PROJECTadmin-web",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bugs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "YOUR-PROJECTadmin-web" }
     ]
    }
   ]
  }
 ]
}